### ISSUE TITLE
QR-Code scanner not working on Samsung with Android 14

### ISSUE THREAD

**Issue by HereIsNils** [ionic-team/capacitor-barcode-scanner#30]
### Project:
Ionic/Angular: 8.3.2
Capacitor: 6.1.2
barcode-scanner: 1.0.1

### Test devices:
Specs of the phone where the plugin is not working on:
One UI-Version: 6.0
Android: 14
Productname: Galaxy A53 5G

Other test devices, where the plugin is working on:
Iphone 11 Pro (IOS 18.0), Ipad Pro 4th generation (IOS 18.0.1), Xiaomi Redmi Note 9 (Android 12), Lenovo P11 (Android 13), Emulated Pixel 8 Fold (Android 14 & 15)

### Issue:
We are trying to use this plugin and got it to work on IOS 18 and older android phones and some android 35 simulators, as listed above.
When scanning a qr code with a Samsung galaxy A53 5G, no result is returned. The qr code is not being recognized by the plugin and therefore the camera just stays open. We tried to scan the qr code many times, from different angles, different light conditions, but couldnt get the code to be scanned. With the normal camera app, the qr code is recoginzed instantly.
Code that opens the camera:
```typescript
openScanner() {
    if (this.platform.is('capacitor')) {
      CapacitorBarcodeScanner.scanBarcode({
        hint: CapacitorBarcodeScannerTypeHint.QR_CODE,
        scanInstructions: TranslatePipe.get("ScanDevice"),
        scanText: TranslatePipe.get("ScanDevice")
      }).then(response => {
        let result = response.ScanResult.split(";");
        if (result.length > 1) {
          this.token = result[0];
          this.deviceID = result[1];
          setTimeout(() => {
            this.claimDevice();
          }, 100);
        } else {
          //TODO: Show Toast
        }
      });
```

We also tried it with the .ALL typeHint, but got no result either.
We also added android specific configuration: 
```typescript
    android: {
          scanningLibrary: CapacitorBarcodeScannerAndroidScanningLibrary.ZXING
        }
```
and tried both ZXING and mlkit, but with no result either. 

Is there a known problem with samsung phones?

**Comment by cemkarahan84** [comment]
Take a look at my PR we got the same issue and found a fix for Android

The plugin try to get android configuration in an object called native but doesn't exist in the definition. 

You have to fix the definition or modify the plugin itself.

**Comment by Geschan** [comment]
We have observed the same issue on Samsung devices with Android 14.

**Comment by DevDianDankie** [comment]
Hello, I just made an issue with my findings - I suspect this is related.

I noticed on android any qr code that is light on dark background does not work

But if invert it so it is dark on light it will pick it up

**Comment by jaroslavstefanec** [comment]
Hello, 
has anyone found out how to fix this issue or what is causing it?

**Comment by rg4sun** [comment]
> Same issue on Galaxy XCover7 , Android: 14, barcode-scanner: 1.0.1. Works on iOS devices.

Further debugging it, got the following error message from logcat:

`FATAL EXCEPTION: main
Process: com.rg4sun.bloodhero.app, PID: 17998
java.lang.NoSuchMethodError: No static method rememberComposableLambda(IZLjava/lang/Object;Landroidx/compose/runtime/Composer;I)Landroidx/compose/runtime/internal/ComposableLambda; in class Landroidx/compose/runtime/internal/ComposableLambdaKt; or its super classes (declaration of 'androidx.compose.runtime.internal.ComposableLambdaKt' appears in /data/app/~~C1IfwjEY_CI2p53yULMkzQ==/com.rg4sun.bloodhero.app-ZPZoF7WfX-T48HqvL5GY2Q==/base.apk)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity$onCreate$3.invoke(OSBARCScannerActivity.kt:204)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity$onCreate$3.invoke(OSBARCScannerActivity.kt:198)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:194)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:156)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:155)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:155)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3373)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3363)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3363)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3298)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:966)
`
